#! /bin/bash

ssh qian-test1 -t "cd TileDB-multinode; make mpi-prod"
ssh qian-test2 -t "cd TileDB-multinode; make mpi-prod"
ssh qian-test3 -t "cd TileDB-multinode; make mpi-prod"
ssh qian-test4 -t "cd TileDB-multinode; make mpi-prod"
ssh qian-test5 -t "cd TileDB-multinode; make mpi-prod"
ssh qian-test6 -t "cd TileDB-multinode; make mpi-prod"
ssh qian-test7 -t "cd TileDB-multinode; make mpi-prod"
ssh qian-test8 -t "cd TileDB-multinode; make mpi-prod"

#1 = datatsize, 2 = number of nodes including master
#ex: ./runner 500 8
make mpi-prod && mpiexec -n $2 -f machinefile_prod ./mpi_main $1
